/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <led.h>
#include <uart.h>
//#include <timebase.h>
#include "rtoskernel.h"
#define ROUND_ROBIN_PERIOD		1 //MS
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
uint32_t cntTask0, cntTask1, cntTask2, cntTask3, cntTask4;
int32_t semaphore1, semaphore2;
/*int main_cool(){
	while(1){
		printf("Cool On\n\r");
		delay(4);
		printf("Cool Off\n\r");
		delay(4);
	}
	return 0;
}

int main_hot(){
	while(1){
		printf("Hot On\n\r");
		delay(4);
		printf("Hot Off\n\r");
		delay(4);
	}
	return 0;
}*/

void park_mode(){
	printf("Park Mode\n\r");
}
void reverse_mode(){
	printf("Reverse Mode\n\r");
}
void neutral_mode(){
	printf("Neutral Mode\n\r");
}
void drive_mode(){
	printf("Drive Mode\n\r");
}

void task3(){
	cntTask3++;
	//drive_mode();
	//rtosThreadYield();
}

void task0(){
	while(1){
		cntTask0++;
		rtosSemaphoreCntTake(&semaphore1);
		drive_mode();
		rtosSemaphoreCntGive(&semaphore1);
		//rtosThreadYield();
	}
}

void task1(){
	while(1){
		cntTask1++;
		//rtosThreadYield();
	}
}

void task2(){
	while(1){
		cntTask2++;
		//rtosThreadYield();
		rtosSemaphoreCntTake(&semaphore1);
		park_mode();
		rtosSemaphoreCntGive(&semaphore1);
		//rtosThreadYield();
	}
}

int main(void)
{
	led_init();
	uart_tx_init();
	tim2_1hz_interrupt_init();
//	timebase_init();
//    /* Loop forever */
//	main_hot();//Therad1
//	main_cool();//Thread2
//	for(;;){
//		led_on();
//		//for(int i =0; i<90000; i++){};
//		delay(4);
//		led_off();
//		printf("Hi from M4\n\r");
//		delay(4);
//	}
	rtosSempahoreInit(&semaphore1, 1);
	rtosSempahoreInit(&semaphore2, 0);
	rtosKernelInit();
	rtosKernelAddThread(&task0, &task1, &task2);
	rtosKernelLaunch(ROUND_ROBIN_PERIOD);
	while(1){

	}
}

void TIM2_IRQHandler(){
	//Clear the interrupt flag
	TIM2->SR &= ~SR_UIF;
	cntTask4++;
}
