/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <led.h>
#include <uart.h>
#include <timebase.h>
#include <rtoskernel.h>
#define ROUND_ROBIN_PERIOD		200 //MS

uint32_t cntTask0, cntTask1, cntTask2;
int32_t semaphore1, semaphore2;

static void thread0(){
  uint32_t oldTick = get_tick();
  while(1){
	if(get_tick()-oldTick >= 1){
		cntTask0++;
	  oldTick = get_tick();
	}
	delay(1);
  }
}

static void thread1(){
  uint32_t oldTick = get_tick();
  while(1){
	if(get_tick()-oldTick >= 1){
		cntTask1++;
	  oldTick = get_tick();
	}
	if(cntTask1==70){
		rtosThreadYield();
	}
  }
}

static void thread2(){
  uint32_t oldTick = get_tick();
  while(1){
	if(get_tick()-oldTick >= 1){
		cntTask2++;
	  oldTick = get_tick();
	}
  }
}


int main(void)
{
	led_init();
	uart_tx_init();
	tim2_1MS_tick_init();
	rtosKernelClkInit();
	rtosKernelAddThread(&thread0, 0);
	rtosKernelAddThread(&thread1, 1);
	rtosKernelAddThread(&thread2, 2);
	rtosKernelLaunch(ROUND_ROBIN_PERIOD);
	while(1){}
}


