/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <led.h>
#include <uart.h>
#include <timebase.h>
#include <rtoskernel.h>
#define ROUND_ROBIN_PERIOD		10 //MS

uint32_t cntTask0, cntTask1, cntTask2;
int32_t semaphore1, semaphore2;

void park_mode(){
	printf("Park Mode\n\r");
}
void reverse_mode(){
	printf("Reverse Mode\n\r");
}
void neutral_mode(){
	printf("Neutral Mode\n\r");
}
void drive_mode(){
	printf("Drive Mode\n\r");
}

void task0(){
	while(1){
		cntTask0++;
		rtosSemaphoreCntTake(&semaphore1);
		drive_mode();
		rtosSemaphoreCntGive(&semaphore1);
		//rtosThreadYield();
		delay(7);
	}
}

void task1(){
	while(1){
		cntTask1++;
		//rtosThreadYield();
	}
}

void task2(){
	while(1){
		cntTask2++;
		//rtosThreadYield();
		rtosSemaphoreCntTake(&semaphore1);
		park_mode();
		rtosSemaphoreCntGive(&semaphore1);
		//rtosThreadYield();
		delay(3);
	}
}

int main(void)
{
	led_init();
	uart_tx_init();
	tim2_1MS_tick_init();

//	for(;;){
//		led_on();
//		//for(int i =0; i<90000; i++){};
//		delay(4);
//		led_off();
//		printf("Hi from M4\n\r");
//		delay(4);
//	}
	rtosSempahoreInit(&semaphore1, 1);
	rtosSempahoreInit(&semaphore2, 0);
	rtosKernelClkInit();
	rtosKernelAddThread(&task0, 0);
	rtosKernelAddThread(&task1, 1);
	rtosKernelAddThread(&task2, 2);
	rtosKernelAddThread(&task2, 3);
	rtosKernelAddThread(&task2, 4);
	rtosKernelLaunch(ROUND_ROBIN_PERIOD);
	while(1){

	}
}


